apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-agent
  template:
    metadata:
      labels:
        app: adk-agent
    spec:
      serviceAccount: adk-ray-agent-sa
      containers:
      - name: adk-agent
        image: us-central1-docker.pkg.dev/gke-ai-open-models/adk-ray-mcp-repo/adk-agent:latest
        resources:
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1Gi
            cpu: 2
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: '8080'
          - name: GOOGLE_CLOUD_PROJECT
            value: 'gke-ai-open-models'
          - name: GOOGLE_CLOUD_LOCATION
            value: 'us-central1'
          - name: GOOGLE_GENAI_USE_VERTEXAI
            value: 'False'
          - name: WEATHER_MCP_SERVER_HOST
            value: 'weather-mcp-server'
          - name: WEATHER_SERVER_PORT
            value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: adk-agent
spec:       
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: adk-agent
