apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-cocktail-server
  labels:
    app: mcp-cocktail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-cocktail-server
  template:
    metadata:
      labels:
        app: mcp-cocktail-server
    spec:
      serviceAccount: adk-ray-agent-sa
      containers:
      - name: mcp-cocktail-container
        image: us-central1-docker.pkg.dev/gke-ai-open-models/adk-ray-mcp-repo/mcp-cocktail-server:latest
        ports:
        - name: http-mcp
          containerPort: 50051
        env:
        - name: MCP_SERVER_HOST
          value: "0.0.0.0"
        - name: MCP_SERVER_PORT
          value: "50051"
        resources:
          requests:
            cpu: "300m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          tcpSocket:
            port: http-mcp # Use the port name
          initialDelaySeconds: 15 # Time to wait before first probe
          periodSeconds: 10    # How often to probe
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: http-mcp # Use the port name
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-cocktail-service
spec:
  type: ClusterIP # Only accessible within the Kubernetes cluster
  selector:
    app: mcp-cocktail-server # Must match the labels of the Pods in the Deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-mcp
